# Generated by Django 4.2.5 on 2023-09-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='questions',
        ),
    ]
